// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv3KVEiEisTZImqGmH1bD8dAwYF1gdIxI',
    appId: '1:977355559764:web:164b6fb51cdd4dcbd1eec1',
    messagingSenderId: '977355559764',
    projectId: 'gpa-calcos',
    authDomain: 'gpa-calcos.firebaseapp.com',
    storageBucket: 'gpa-calcos.appspot.com',
    measurementId: 'G-REMD0HM7V0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-hVqJrYv2Uj3FAZAQSw1Uq4mDxbrmKEs',
    appId: '1:977355559764:android:12776b13733a6b7ad1eec1',
    messagingSenderId: '977355559764',
    projectId: 'gpa-calcos',
    storageBucket: 'gpa-calcos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI3HoJTPVSIuGwwuUU2LyFa14LlwAzEIA',
    appId: '1:977355559764:ios:aad5df0992337245d1eec1',
    messagingSenderId: '977355559764',
    projectId: 'gpa-calcos',
    storageBucket: 'gpa-calcos.appspot.com',
    iosClientId: '977355559764-4sqoc4ancuutk0l87bulm4b4r5u2gbnf.apps.googleusercontent.com',
    iosBundleId: 'com.example.gpaCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI3HoJTPVSIuGwwuUU2LyFa14LlwAzEIA',
    appId: '1:977355559764:ios:dade38d1c352af4fd1eec1',
    messagingSenderId: '977355559764',
    projectId: 'gpa-calcos',
    storageBucket: 'gpa-calcos.appspot.com',
    iosClientId: '977355559764-k25n5hd7anm6civmea2ij9u007d3n5h0.apps.googleusercontent.com',
    iosBundleId: 'com.example.gpaCalculator.RunnerTests',
  );
}
